services:
  nginx:
    build:
      context: .
      dockerfile: /docker/nginx/Dockerfile
    image: new-api/nginx
    container_name: new-api-webserver
    ports:
      - "80:80"
    volumes:
      - .:/data:delegated
      - ./docker/nginx/hosts/app.local.conf:/etc/nginx/conf.d/app.local.conf:ro
      - ./var/log/nginx:/var/log/nginx
    networks:
      - new-network
    restart: always

  app:
    build:
      context: .
      dockerfile: /docker/php/Dockerfile
    image: new-api/php
    container_name: new-api-app
    volumes:
      - .:/data:delegated
      - ~/.composer:/home/www-data/.composer:cached
    env_file:
      - .env
    depends_on:
      - database
    working_dir: /data
    networks:
      - new-network
    tty: true

  
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    container_name: new-api-database
    env_file:
      - .env
    ports:
      - "5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - new-network

  redis:
    image: redis:alpine
    container_name: new-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - new-network

volumes:
  elastic_data:
  database_data:
  redis_data:
  database_test_data:

networks:
  new-network:
    driver: bridge
